FROM python:3.10.4-slim-bullseye
RUN apt-get update -y && apt-get upgrade -y
RUN pip install --upgrade pip

COPY requirements.txt /srv/
RUN pip install -r /srv/requirements.txt
COPY docker/entrypoint.sh /srv/
COPY web/*.py /srv/web/

ENTRYPOINT srv/entrypoint.sh


