FROM python:3.12.9-slim-bookworm as generate_data
RUN apt-get update -y && apt-get upgrade -y && apt-get install unzip wget -y
#RUN wget -q  https://www.softcatala.org/pub/softcatala/punctuation/model.zip
RUN wget -q  https://riuraueditors.cat/pub/model.zip
RUN unzip model.zip -d /model/

FROM python:3.12.9-slim-bookworm
RUN apt-get update -y && apt-get upgrade -y && apt-get install gcc -y 
RUN pip install --upgrade pip

COPY --from=generate_data model/* /srv/web/model/

COPY requirements.txt /srv/
RUN pip install -r /srv/requirements.txt
COPY docker/entrypoint.sh /srv/
COPY web/*.py /srv/web/

ENTRYPOINT srv/entrypoint.sh


